/// Mapping of numeric butterfly IDs to their corresponding species names.
/// Title-cased for consistent matching with `butterflyInfoMap`.
const Map<int, String> idToSpeciesName = {
  1: 'Adonis',
  2: 'African Giant Swallowtail',
  3: 'American Snoot',
  4: 'An 88',
  5: 'Appollo',
  6: 'Arcigera Flower Moth',
  7: 'Atala',
  8: 'Atlas Moth',
  9: 'Banded Orange Heliconian',
  10: 'Banded Peacock',
  11: 'Banded Tiger Moth',
  12: 'Beckers White',
  13: 'Bird Cherry Ermine Moth',
  14: 'Black Hairstreak',
  15: 'Blue Morpho',
  16: 'Blue Spotted Crow',
  17: 'Brookes Birdwing',
  18: 'Brown Argus',
  19: 'Brown Siproeta',
  20: 'Cabbage White',
  21: 'Cairns Birdwing',
  22: 'Chalk Hill Blue',
  23: 'Checquered Skipper',
  24: 'Chestnut',
  25: 'Cinnabar Moth',
  26: 'Clearwing Moth',
  27: 'Cleopatra',
  28: 'Clodius Parnassian',
  29: 'Clouded Sulphur',
  30: 'Comet Moth',
  31: 'Common Banded Awl',
  32: 'Common Wood-Nymph',
  33: 'Copper Tail',
  34: 'CrecenT',
  35: 'Crimson Patch',
  36: 'Danaid Eggfly',
  37: 'Eastern Coma',
  38: 'Eastern Dapple White',
  39: 'Eastern Pine Elfin',
  40: 'Elbowed Pierrot',
  41: 'Emperor Gum Moth',
  42: 'Garden Tiger Moth',
  43: 'Giant Leopard Moth',
  44: 'Glittering Sapphire',
  45: 'Gold Banded',
  46: 'Great Eggfly',
  47: 'Great Jay',
  48: 'Green Celled Cattleheart',
  49: 'Green Hairstreak',
  50: 'Grey Hairstreak',
  51: 'Hercules Moth',
  52: 'Humming Bird Hawk Moth',
  53: 'Indra Swallow',
  54: 'Io Moth',
  55: 'Iphiclus Sister',
  56: 'Julia',
  57: 'Large Marble',
  58: 'Luna Moth',
  59: 'Madagascan Sunset Moth',
  60: 'Malachite',
  61: 'Mangrove Skipper',
  62: 'Mestra',
  63: 'Metalmark',
  64: 'Milberts Tortoiseshell',
  65: 'Monarch',
  66: 'Mourning Cloak',
  67: 'Oleander Hawk Moth',
  68: 'Orange Oakleaf',
  69: 'Orange Tip',
  70: 'Orchard Swallow',
  71: 'Painted Lady',
  72: 'Paper Kite',
  73: 'Peacock',
  74: 'Pine White',
  75: 'Pipevine Swallow',
  76: 'Polyphemus Moth',
  77: 'Popinjay',
  78: 'Purple Hairstreak',
  79: 'Purplish Copper',
  80: 'Question Mark',
  81: 'Red Admiral',
  82: 'Red Cracker',
  83: 'Red Postman',
  84: 'Red Spotted Purple',
  85: 'Rosy Maple Moth',
  86: 'Scarce Swallow',
  87: 'Silver Spot Skipper',
  88: 'Sixspot Burnet Moth',
  89: 'Sleepy Orange',
  90: 'Sootywing',
  91: 'Southern Dogface',
  92: 'Straited Queen',
  93: 'Tropical Leafwing',
  94: 'Two Barred Flasher',
  95: 'Ulyses',
  96: 'Viceroy',
  97: 'White Lined Sphinx Moth',
  98: 'Wood Satyr',
  99: 'Yellow Swallow Tail',
  100: 'Zebra Long Wing',
};
